# If true Apache Tika will try to open and parse each file for more accurate MimeType detection
# If false Apache Tika will only try to detect MimeType based on the file name extension
core.tools.mets-generator.useFileContentMimeTypeDetection = false

core.plugins.dropdown.parameter.ip_profile[] = sip
core.plugins.dropdown.parameter.ip_profile[] = aip
core.plugins.dropdown.parameter.ip_profile[] = dip

core.plugins.dropdown.parameter.ip_profile[].sip.i18n = mets-generator.ip_profile.sip.title
core.plugins.dropdown.parameter.ip_profile[].aip.i18n = mets-generator.ip_profile.aip.title
core.plugins.dropdown.parameter.ip_profile[].dip.i18n = mets-generator.ip_profile.dip.title
